### ISSUE TITLE
Doesn't seem to respect the .isort.cfg or settings.cfg in the project directory

### ISSUE THREAD

**Issue by NorthIsUp** [thijsdezoete/sublime-text-isort-plugin#15]
Our team uses several editors and it would be nice to have a single source of truth for isort configuration

**Comment by NorthIsUp** [comment]
fixed by #17

**Comment by mnieber** [comment]
Still broken for me, it ignores the setup.cfg in my source tree
